# ---- Build stage ----
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# ---- Runtime stage ----
FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf


COPY --from=builder /app/dist/frontend/browser /usr/share/nginx/html


COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy build output
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
